week2 database assignment
daxiousm/hyf-homework pull request #13
Opened 2020-08-15 21:20 UTC by daxiousm

2020-08-16 06:17 UTC, babakbandpey commented on databases/week2/schoolDatabase.sql
> +    `class_id` int(10) unsigned,
The attribute `class_id `is not belong to the student class.
You need a `class_students `table to save the relations. A class has many students and a student has many classes.

2020-08-16 06:18 UTC, babakbandpey commented on databases/week2/schoolDatabase.sql
> +ALTER  TABLE class ADD  status ENUM('notstarted', 'ongoing', 'finished') NOT NULL;
The default value must be defined for the new column

2020-08-16 06:18 UTC, babakbandpey commented on databases/week2/schoolDatabase.sql
> +USE school;
Which database is this one?

2020-08-16 11:33 UTC, daxiousm commented on databases/week2/schoolDatabase.sql
> +USE school;
the schoolDatabase

2020-08-17 10:48 UTC, babakbandpey commented on databases/week2/schoolDatabase.sql
> +USE school;
You need to correct the PR

2020-08-24 18:00 UTC, daxiousm commented on databases/week2/part4.sql
> +
i tried creating relationship between singres, albums and songs, please check it out

2020-08-26 07:41 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `songs_AlbumsId` INT NOT NULL,
remove

2020-08-26 07:41 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `songs_SingersId` INT NOT NULL,
remove

2020-08-26 07:42 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `TrackId` INT NOT NULL AUTO_INCREMENT,
id

2020-08-26 07:42 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `SingersId` INT NOT NULL,
singer_id

2020-08-26 07:42 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `AlbumsId` INT NOT NULL,
album_id

2020-08-26 07:43 UTC, babakbandpey commented on databases/week2/music2.sql
> +  PRIMARY KEY (`TrackId`, `SingersId`, `AlbumsId`))
add singer_id and album_id as foreign keys with reference to their respected tables

2020-08-26 07:43 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `AlbumsId` INT NOT NULL AUTO_INCREMENT,
id

2020-08-26 07:43 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `SingersId` INT NOT NULL,
remove

2020-08-26 07:43 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `AlbumTitle` VARCHAR(45) NOT NULL,
title

2020-08-26 07:44 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `songs_TrackId` INT NOT NULL,
track_id could be in songs table

2020-08-26 07:44 UTC, babakbandpey commented on databases/week2/music2.sql
> +  PRIMARY KEY (`AlbumsId`, `SingersId`, `AlbumTitle`, `songs_TrackId`, `songs_SingersId`, `songs_AlbumsId`),
only the id from the table is enough

2020-08-26 07:45 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `SingersId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
id

2020-08-26 07:45 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `SingerInfo` VARCHAR(45) NULL,
Bio/info

2020-08-26 07:45 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `Albums_AlbumsId` INT NOT NULL,
remove

2020-08-26 07:45 UTC, babakbandpey commented on databases/week2/music2.sql
> +  `Albums_AlbumTitle` VARCHAR(45) NOT NULL,
remove

2020-08-26 07:45 UTC, babakbandpey commented on databases/week2/music2.sql
> +  PRIMARY KEY (`SingersId`),
id

2020-08-26 07:47 UTC, babakbandpey commented on databases/week2/music2.sql
> +-- -----------------------------------------------------
not needed

2020-08-26 07:50 UTC, babakbandpey commented on databases/week2/part1.sql
> +INSERT INTO task (title, description, created, updated, due_date, status_id, user_id)
take a look at this and make it work with the week 2 assignment

2020-08-26 07:53 UTC, babakbandpey commented on databases/week2/part1.sql
> +
Remember to delete from `user_tasks `by `task_id `and then delete from `tasks`

2020-08-26 08:03 UTC, babakbandpey requested changes
Hello,

Please make these changes.
Thanks

2020-09-16 08:06 UTC, merged